---
version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/node:8.10.0
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: db1
          MYSQL_USER: apurva@localhost
          MYSQL_PASSWORD: Rajuabha25!
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm run build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test
  build:
    docker:
      - image: circleci/node:8.10.0
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test
workflows:
  version: 2
  pr-check:
    jobs:
    - pr_check:
        filters:
          branches:
            ignore:
            - master
  build_deploy:
    jobs:
    - build:
        filters:
          branches:
            only:
            - master